FROM node:16-alpine

WORKDIR /app

# VOLUME /data

COPY . .

RUN yarn install && yarn build

EXPOSE 4000

ENV MONGO_URL=mongodb+srv://admin:admin@sortlog-dev.tz5kdhn.mongodb.net/sortlog-dev
ENV auth_encryption_salt=some-salt
ENV PORT=4000

# CMD ["cp", "package.json", "data/"]
ENTRYPOINT ["cp", "-r", "package.json", "node_modules", "dist", "data/"]